--SELECT

SELECT * FROM CUSTOMER
SELECT CUSTOMERNAME, BIRTHDATE FROM CUSTOMER

--INSERT

INSERT INTO CUSTOMER 
([CUSTOMERNAME], [CITY], [DISTRICT], [BIRTHDATE], [GENDER])
VALUES
('MAHMUT ARSLAN', 'ÝZMÝR', 'BORNOVA', '1992-04-04', 'E')

--UPDATE

UPDATE CUSTOMER SET AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())

--DELETE

SELECT * INTO CUSTOMERYEDEK FROM CUSTOMER
DELETE FROM CUSTOMER

--WHERE

SELECT * FROM CUSTOMER WHERE AGE > 30
SELECT * FROM CUSTOMER WHERE CUSTOMERNAME LIKE 'ZEYNEP%'

--AND/OR

SELECT * FROM CUSTOMER WHERE CITY = 'ANKARA' AND GENDER = 'K'
SELECT * FROM CUSTOMER WHERE CITY = 'ANKARA' OR GENDER = 'K'

--DISTINCT

SELECT DISTINCT CUSTOMERNAME FROM CUSTOMER

--ORDER BY

SELECT * FROM CUSTOMER ORDER BY AGE DESC

--TOP

SELECT TOP 1 * FROM CUSTOMER
SELECT TOP 50 PERCENT * FROM CUSTOMER -- YÜZDE 50