--SELECT

SELECT * FROM CUSTOMER
SELECT CUSTOMERNAME, BIRTHDATE FROM CUSTOMER

--INSERT

INSERT INTO CUSTOMER 
([CUSTOMERNAME], [CITY], [DISTRICT], [BIRTHDATE], [GENDER])
VALUES
('MAHMUT ARSLAN', 'ÝZMÝR', 'BORNOVA', '1992-04-04', 'E')

--UPDATE

UPDATE CUSTOMER SET AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())

--DELETE

SELECT * INTO CUSTOMERYEDEK FROM CUSTOMER
DELETE FROM CUSTOMER

--WHERE

SELECT * FROM CUSTOMER WHERE AGE > 30
SELECT * FROM CUSTOMER WHERE CUSTOMERNAME LIKE 'ZEYNEP%'

--AND/OR

SELECT * FROM CUSTOMER WHERE CITY = 'ANKARA' AND GENDER = 'K'
SELECT * FROM CUSTOMER WHERE CITY = 'ANKARA' OR GENDER = 'K'

--DISTINCT

SELECT DISTINCT CUSTOMERNAME FROM CUSTOMER

--ORDER BY

SELECT * FROM CUSTOMER ORDER BY AGE DESC

--TOP

SELECT TOP 1 * FROM CUSTOMER
SELECT TOP 50 PERCENT * FROM CUSTOMER -- YÜZDE 50

--Aggregate Functions

SELECT SUM(LINENET), COUNT(*), MIN(LINENET), MAX(LINENET) FROM SALES where BRANCH = 'Manisa Subesi'

--GROUP BY 

SELECT BRANCH, COUNT(*) AS 'TOPLAM SATIS' FROM SALES GROUP BY BRANCH
SELECT BRANCH, COUNT(*) AS 'TOPLAM SATIS' FROM SALES GROUP BY BRANCH HAVING COUNT(*) > 5000 ORDER BY 2 DESC

-- JOIN

SELECT * FROM ETRADE2..USER_
JOIN ETRADE2..ADDRES ON USER_.ID = ADDRES.USERID
WHERE USER_.ID = 1

-- INNER JOIN
SELECT * FROM ETRADE2..USER_
INNER JOIN ETRADE2..ADDRES ON USER_.ID = ADDRES.USERID
WHERE USER_.ID = 1

-- LEFT, RIGHT JOIN

SELECT * FROM ETRADE2..USER_
LEFT JOIN ETRADE2..ADDRES ON USER_.ID = ADDRES.USERID
WHERE USER_.ID IN (100,101,102)

-- ALIAS 

SELECT * FROM ETRADE2..USER_ AS U
